// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClKboA_fiJRzDojA9rXo6L0BpOiTBP_wQ',
    appId: '1:479253739993:web:2e3bd9a5efddceca9481c8',
    messagingSenderId: '479253739993',
    projectId: 'indrive-entregas-villazon',
    authDomain: 'indrive-entregas-villazon.firebaseapp.com',
    storageBucket: 'indrive-entregas-villazon.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMxxtEW9KjPsCARxdf1QHvShKaUUXJu3U',
    appId: '1:479253739993:android:21c03a01b7c1a74c9481c8',
    messagingSenderId: '479253739993',
    projectId: 'indrive-entregas-villazon',
    storageBucket: 'indrive-entregas-villazon.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJGkNM-c3dPHGvQ7bDK3NRPKxtKwoP5Yg',
    appId: '1:479253739993:ios:28698111d0cf52509481c8',
    messagingSenderId: '479253739993',
    projectId: 'indrive-entregas-villazon',
    storageBucket: 'indrive-entregas-villazon.firebasestorage.app',
    iosBundleId: 'com.example.indriveApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJGkNM-c3dPHGvQ7bDK3NRPKxtKwoP5Yg',
    appId: '1:479253739993:ios:28698111d0cf52509481c8',
    messagingSenderId: '479253739993',
    projectId: 'indrive-entregas-villazon',
    storageBucket: 'indrive-entregas-villazon.firebasestorage.app',
    iosBundleId: 'com.example.indriveApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClKboA_fiJRzDojA9rXo6L0BpOiTBP_wQ',
    appId: '1:479253739993:web:870414c06b80935a9481c8',
    messagingSenderId: '479253739993',
    projectId: 'indrive-entregas-villazon',
    authDomain: 'indrive-entregas-villazon.firebaseapp.com',
    storageBucket: 'indrive-entregas-villazon.firebasestorage.app',
  );
}
